import type { ToolDefinition } from '@/types';

export const TOOL_DEFINITIONS: Record<string, ToolDefinition> = {
  cursor: {
    id: 'cursor',
    name: 'Cursor',
    category: 'code_assistant',
    alternatives: ['windsurf', 'github_copilot'],
    plans: [
      {
        id: 'hobby',
        name: 'Hobby',
        pricePerSeat: 0,
        isTeamPlan: false,
        bestFor: ['coding'],
        features: ['2000 completions/mo', 'GPT-4o mini based'],
        officialPricingUrl: 'https://cursor.sh/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'pro',
        name: 'Pro',
        pricePerSeat: 20,
        isTeamPlan: false,
        bestFor: ['coding'],
        features: ['Unlimited completions', 'GPT-4/Claude Sonnet', '500 fast requests/mo'],
        officialPricingUrl: 'https://cursor.sh/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'business',
        name: 'Business',
        pricePerSeat: 40,
        isTeamPlan: true,
        minSeats: 1,
        bestFor: ['coding'],
        features: ['Everything in Pro', 'Admin dashboard', 'SSO', 'Usage analytics', 'Privacy mode on by default'],
        officialPricingUrl: 'https://cursor.sh/pricing',
        verifiedDate: '2026-05-21',
      },
    ],
  },

  github_copilot: {
    id: 'github_copilot',
    name: 'GitHub Copilot',
    category: 'code_assistant',
    alternatives: ['cursor', 'windsurf'],
    plans: [
      {
        id: 'individual',
        name: 'Individual',
        pricePerSeat: 10,
        isTeamPlan: false,
        bestFor: ['coding'],
        features: ['Code completions', 'Chat in IDE', 'CLI support'],
        officialPricingUrl: 'https://github.com/features/copilot',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'business',
        name: 'Business',
        pricePerSeat: 19,
        isTeamPlan: true,
        bestFor: ['coding'],
        features: ['Everything Individual', 'Organization management', 'Audit logs', 'Policy controls'],
        officialPricingUrl: 'https://github.com/features/copilot',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'enterprise',
        name: 'Enterprise',
        pricePerSeat: 39,
        isTeamPlan: true,
        bestFor: ['coding'],
        features: ['Everything Business', 'Custom models fine-tuning', 'PR summaries', 'Knowledge bases'],
        officialPricingUrl: 'https://github.com/features/copilot',
        verifiedDate: '2026-05-21',
      },
    ],
  },

  claude: {
    id: 'claude',
    name: 'Claude (Anthropic)',
    category: 'llm_chat',
    alternatives: ['chatgpt', 'gemini'],
    plans: [
      {
        id: 'free',
        name: 'Free',
        pricePerSeat: 0,
        isTeamPlan: false,
        bestFor: ['writing', 'research', 'mixed'],
        features: ['Limited messages', 'Claude Sonnet access'],
        officialPricingUrl: 'https://claude.ai/upgrade',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'pro',
        name: 'Pro',
        pricePerSeat: 20,
        isTeamPlan: false,
        bestFor: ['writing', 'research', 'coding', 'mixed'],
        features: ['5x more usage than Free', 'Claude Opus access', 'Projects', 'Priority access'],
        officialPricingUrl: 'https://claude.ai/upgrade',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'max',
        name: 'Max',
        pricePerSeat: 100,
        isTeamPlan: false,
        bestFor: ['research', 'data', 'coding'],
        features: ['20x usage vs Free', 'All models', 'Extended thinking', 'Higher limits'],
        officialPricingUrl: 'https://claude.ai/upgrade',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'team',
        name: 'Team',
        pricePerSeat: 30,
        isTeamPlan: true,
        minSeats: 5,
        bestFor: ['mixed', 'writing', 'research'],
        features: ['Everything Pro', 'Shared Projects', 'Admin console', 'Higher rate limits'],
        officialPricingUrl: 'https://claude.ai/upgrade',
        verifiedDate: '2026-05-21',
      },
    ],
  },

  chatgpt: {
    id: 'chatgpt',
    name: 'ChatGPT (OpenAI)',
    category: 'llm_chat',
    alternatives: ['claude', 'gemini'],
    plans: [
      {
        id: 'free',
        name: 'Free',
        pricePerSeat: 0,
        isTeamPlan: false,
        bestFor: ['writing', 'mixed'],
        features: ['GPT-4o mini', 'Limited GPT-4o', 'Basic features'],
        officialPricingUrl: 'https://openai.com/chatgpt/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'plus',
        name: 'Plus',
        pricePerSeat: 20,
        isTeamPlan: false,
        bestFor: ['writing', 'research', 'mixed'],
        features: ['GPT-4o full access', 'DALL-E image gen', 'Advanced data analysis', 'Custom GPTs'],
        officialPricingUrl: 'https://openai.com/chatgpt/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'team',
        name: 'Team',
        pricePerSeat: 30,
        isTeamPlan: true,
        minSeats: 2,
        bestFor: ['writing', 'research', 'mixed'],
        features: ['Everything Plus', 'Shared GPTs', 'Admin workspace', 'Higher rate limits'],
        officialPricingUrl: 'https://openai.com/chatgpt/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'enterprise',
        name: 'Enterprise',
        pricePerSeat: 60,  // Estimated; OpenAI doesn't publish exact price
        isTeamPlan: true,
        bestFor: ['mixed'],
        features: ['Unlimited GPT-4o', 'SSO', 'Custom retention', 'Advanced security'],
        officialPricingUrl: 'https://openai.com/chatgpt/pricing',
        verifiedDate: '2026-05-21',
      },
    ],
  },

  anthropic_api: {
    id: 'anthropic_api',
    name: 'Anthropic API (Direct)',
    category: 'llm_api',
    alternatives: ['openai_api'],
    plans: [
      {
        id: 'haiku',
        name: 'Claude Haiku 3.5',
        pricePerSeat: 0,  // Usage-based: $0.80/MTok input, $4/MTok output
        isTeamPlan: false,
        bestFor: ['coding', 'data'],
        features: ['$0.80/MTok input', '$4/MTok output', 'Fastest model', 'Best cost/performance'],
        officialPricingUrl: 'https://www.anthropic.com/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'sonnet',
        name: 'Claude Sonnet 4',
        pricePerSeat: 0,  // Usage-based: $3/MTok input, $15/MTok output
        isTeamPlan: false,
        bestFor: ['coding', 'research', 'mixed'],
        features: ['$3/MTok input', '$15/MTok output', 'Best balance speed/intelligence'],
        officialPricingUrl: 'https://www.anthropic.com/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'opus',
        name: 'Claude Opus 4',
        pricePerSeat: 0,  // Usage-based: $15/MTok input, $75/MTok output
        isTeamPlan: false,
        bestFor: ['research', 'data'],
        features: ['$15/MTok input', '$75/MTok output', 'Most capable model'],
        officialPricingUrl: 'https://www.anthropic.com/pricing',
        verifiedDate: '2026-05-21',
      },
    ],
  },

  openai_api: {
    id: 'openai_api',
    name: 'OpenAI API (Direct)',
    category: 'llm_api',
    alternatives: ['anthropic_api'],
    plans: [
      {
        id: 'gpt4o_mini',
        name: 'GPT-4o mini',
        pricePerSeat: 0,  // Usage-based: $0.15/MTok input, $0.60/MTok output
        isTeamPlan: false,
        bestFor: ['coding', 'writing'],
        features: ['$0.15/MTok input', '$0.60/MTok output', 'Most cost-efficient'],
        officialPricingUrl: 'https://openai.com/api/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'gpt4o',
        name: 'GPT-4o',
        pricePerSeat: 0,  // Usage-based: $2.50/MTok input, $10/MTok output
        isTeamPlan: false,
        bestFor: ['research', 'coding', 'mixed'],
        features: ['$2.50/MTok input', '$10/MTok output', 'Flagship model'],
        officialPricingUrl: 'https://openai.com/api/pricing',
        verifiedDate: '2026-05-21',
      },
    ],
  },

  gemini: {
    id: 'gemini',
    name: 'Gemini (Google)',
    category: 'llm_chat',
    alternatives: ['claude', 'chatgpt'],
    plans: [
      {
        id: 'free',
        name: 'Free',
        pricePerSeat: 0,
        isTeamPlan: false,
        bestFor: ['writing', 'mixed'],
        features: ['Gemini 1.5 Pro', 'Limited usage', 'Google integrations'],
        officialPricingUrl: 'https://gemini.google.com/advanced',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'advanced',
        name: 'Gemini Advanced',
        pricePerSeat: 20,
        isTeamPlan: false,
        bestFor: ['research', 'mixed'],
        features: ['Gemini Ultra', '1M context window', 'Google One benefits'],
        officialPricingUrl: 'https://gemini.google.com/advanced',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'business',
        name: 'Gemini for Workspace Business',
        pricePerSeat: 30,
        isTeamPlan: true,
        bestFor: ['writing', 'mixed'],
        features: ['Gemini in Google Docs/Sheets/Gmail', 'Team management', 'Admin controls'],
        officialPricingUrl: 'https://workspace.google.com/intl/en/pricing/gemini/',
        verifiedDate: '2026-05-21',
      },
    ],
  },

  windsurf: {
    id: 'windsurf',
    name: 'Windsurf (Codeium)',
    category: 'code_assistant',
    alternatives: ['cursor', 'github_copilot'],
    plans: [
      {
        id: 'free',
        name: 'Free',
        pricePerSeat: 0,
        isTeamPlan: false,
        bestFor: ['coding'],
        features: ['Unlimited completions (free)', 'Chat with Claude Sonnet', '5 fast requests/day'],
        officialPricingUrl: 'https://windsurf.ai/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'pro',
        name: 'Pro',
        pricePerSeat: 15,
        isTeamPlan: false,
        bestFor: ['coding'],
        features: ['Unlimited fast requests', 'All models', 'Advanced agentic features'],
        officialPricingUrl: 'https://windsurf.ai/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'teams',
        name: 'Teams',
        pricePerSeat: 30,
        isTeamPlan: true,
        bestFor: ['coding'],
        features: ['Everything Pro', 'Team management', 'Usage analytics'],
        officialPricingUrl: 'https://windsurf.ai/pricing',
        verifiedDate: '2026-05-21',
      },
    ],
  },
  midjourney: {
    id: 'midjourney',
    name: 'Midjourney',
    category: 'llm_chat',
    alternatives: [],
    plans: [
      {
        id: 'basic',
        name: 'Basic',
        pricePerSeat: 10,
        isTeamPlan: false,
        bestFor: ['mixed'],
        features: ['3.3 hr/mo Fast GPU time', 'Unlimited Relaxed GPU time', 'Personal bot chat'],
        officialPricingUrl: 'https://www.midjourney.com/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'standard',
        name: 'Standard',
        pricePerSeat: 30,
        isTeamPlan: false,
        bestFor: ['mixed'],
        features: ['15 hr/mo Fast GPU time', 'Unlimited Relaxed GPU time', 'General member gallery'],
        officialPricingUrl: 'https://www.midjourney.com/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'pro',
        name: 'Pro',
        pricePerSeat: 60,
        isTeamPlan: false,
        bestFor: ['mixed'],
        features: ['30 hr/mo Fast GPU time', 'Stealth mode image generation', '12 concurrent fast jobs'],
        officialPricingUrl: 'https://www.midjourney.com/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'mega',
        name: 'Mega',
        pricePerSeat: 120,
        isTeamPlan: false,
        bestFor: ['mixed'],
        features: ['60 hr/mo Fast GPU time', 'Stealth mode', '15 concurrent fast jobs'],
        officialPricingUrl: 'https://www.midjourney.com/pricing',
        verifiedDate: '2026-05-21',
      },
    ],
  },
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity',
    category: 'llm_chat',
    alternatives: ['claude', 'chatgpt', 'gemini'],
    plans: [
      {
        id: 'free',
        name: 'Free',
        pricePerSeat: 0,
        isTeamPlan: false,
        bestFor: ['research'],
        features: ['Standard search', 'Copilot (5 queries/4h)', 'Basic model answers'],
        officialPricingUrl: 'https://www.perplexity.ai/pro',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'pro',
        name: 'Perplexity Pro',
        pricePerSeat: 20,
        isTeamPlan: false,
        bestFor: ['research', 'mixed'],
        features: ['Unlimited Pro search', 'Claude 3.5 & GPT-4o selection', 'File uploads', 'API credits ($5/mo)'],
        officialPricingUrl: 'https://www.perplexity.ai/pro',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'enterprise',
        name: 'Enterprise Pro',
        pricePerSeat: 40,
        isTeamPlan: true,
        minSeats: 5,
        bestFor: ['research', 'mixed'],
        features: ['Everything in Pro', 'SOC2 security', 'SSO & SAML', 'Admin console & billing dashboard'],
        officialPricingUrl: 'https://www.perplexity.ai/pro',
        verifiedDate: '2026-05-21',
      },
    ],
  },
  v0: {
    id: 'v0',
    name: 'v0 by Vercel',
    category: 'code_assistant',
    alternatives: ['cursor', 'windsurf'],
    plans: [
      {
        id: 'free',
        name: 'Free',
        pricePerSeat: 0,
        isTeamPlan: false,
        bestFor: ['coding'],
        features: ['Limited generations', 'Community access', 'Web app preview'],
        officialPricingUrl: 'https://v0.dev/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'premium',
        name: 'Premium',
        pricePerSeat: 20,
        isTeamPlan: false,
        bestFor: ['coding'],
        features: ['5000 fast credits/mo', 'Private generations', 'Higher rate limits'],
        officialPricingUrl: 'https://v0.dev/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'team',
        name: 'Team',
        pricePerSeat: 30,
        isTeamPlan: true,
        minSeats: 2,
        bestFor: ['coding'],
        features: ['Shared workspace', 'Team billing & members management', 'Unlimited generations'],
        officialPricingUrl: 'https://v0.dev/pricing',
        verifiedDate: '2026-05-21',
      },
    ],
  },
  elevenlabs: {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    category: 'llm_api',
    alternatives: [],
    plans: [
      {
        id: 'free',
        name: 'Free',
        pricePerSeat: 0,
        isTeamPlan: false,
        bestFor: ['mixed'],
        features: ['10,000 characters/mo', 'Basic text-to-speech', 'Attribution required'],
        officialPricingUrl: 'https://elevenlabs.io/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'starter',
        name: 'Starter',
        pricePerSeat: 5,
        isTeamPlan: false,
        bestFor: ['mixed'],
        features: ['30,000 characters/mo', 'Instant voice cloning', 'Commercial license'],
        officialPricingUrl: 'https://elevenlabs.io/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'creator',
        name: 'Creator',
        pricePerSeat: 22,
        isTeamPlan: false,
        bestFor: ['mixed'],
        features: ['100,000 characters/mo', 'Professional voice cloning', 'High-quality audio outputs'],
        officialPricingUrl: 'https://elevenlabs.io/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'pro',
        name: 'Independent Publisher',
        pricePerSeat: 99,
        isTeamPlan: false,
        bestFor: ['mixed'],
        features: ['500,000 characters/mo', 'Usage dashboard', 'Priority support'],
        officialPricingUrl: 'https://elevenlabs.io/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'scale',
        name: 'Growing Business',
        pricePerSeat: 330,
        isTeamPlan: true,
        bestFor: ['mixed'],
        features: ['2,000,000 characters/mo', 'Dedicated support', 'Volume discounts'],
        officialPricingUrl: 'https://elevenlabs.io/pricing',
        verifiedDate: '2026-05-21',
      },
    ],
  },
  notion_ai: {
    id: 'notion_ai',
    name: 'Notion AI',
    category: 'llm_chat',
    alternatives: ['claude', 'chatgpt'],
    plans: [
      {
        id: 'add_on',
        name: 'AI Add-On',
        pricePerSeat: 10,
        isTeamPlan: false,
        bestFor: ['writing', 'research'],
        features: ['Autofill databases', 'Summarize notes', 'Q&A in docs', 'Write drafts'],
        officialPricingUrl: 'https://www.notion.so/product/ai',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'business_ai',
        name: 'Business + AI bundle',
        pricePerSeat: 25,
        isTeamPlan: true,
        bestFor: ['writing', 'research'],
        features: ['Everything in AI Add-on', 'Private team workspaces', 'SAML SSO', 'Advanced page analytics'],
        officialPricingUrl: 'https://www.notion.so/product/ai',
        verifiedDate: '2026-05-21',
      },
    ],
  },
  deepl: {
    id: 'deepl',
    name: 'DeepL Pro',
    category: 'llm_api',
    alternatives: [],
    plans: [
      {
        id: 'free',
        name: 'Free',
        pricePerSeat: 0,
        isTeamPlan: false,
        bestFor: ['writing'],
        features: ['3 locked documents/mo', '3,000 characters translation', 'Basic glossary'],
        officialPricingUrl: 'https://www.deepl.com/pro',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'starter',
        name: 'Pro Starter',
        pricePerSeat: 10,
        isTeamPlan: false,
        bestFor: ['writing', 'mixed'],
        features: ['Unlimited translation', '5 editable documents/mo', 'Max security data privacy'],
        officialPricingUrl: 'https://www.deepl.com/pro',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'advanced',
        name: 'Pro Advanced',
        pricePerSeat: 33,
        isTeamPlan: true,
        bestFor: ['writing', 'mixed'],
        features: ['20 editable docs/mo', 'Multiple glossaries', 'Team administration dashboard'],
        officialPricingUrl: 'https://www.deepl.com/pro',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'ultimate',
        name: 'Pro Ultimate',
        pricePerSeat: 68,
        isTeamPlan: true,
        bestFor: ['writing', 'mixed'],
        features: ['100 editable docs/mo', 'Everything in Advanced', 'Single Sign-On (SSO)'],
        officialPricingUrl: 'https://www.deepl.com/pro',
        verifiedDate: '2026-05-21',
      },
    ],
  },
  jasper: {
    id: 'jasper',
    name: 'Jasper',
    category: 'llm_chat',
    alternatives: ['claude', 'chatgpt'],
    plans: [
      {
        id: 'creator',
        name: 'Creator',
        pricePerSeat: 49,
        isTeamPlan: false,
        bestFor: ['writing'],
        features: ['1 brand voice', '50+ templates', 'SEO mode access'],
        officialPricingUrl: 'https://www.jasper.ai/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'pro',
        name: 'Pro',
        pricePerSeat: 69,
        isTeamPlan: true,
        minSeats: 1,
        bestFor: ['writing'],
        features: ['3 brand voices', '3 team seats available', 'Jasper Art image generator', 'Document collaboration'],
        officialPricingUrl: 'https://www.jasper.ai/pricing',
        verifiedDate: '2026-05-21',
      },
      {
        id: 'business',
        name: 'Business',
        pricePerSeat: 129,
        isTeamPlan: true,
        minSeats: 5,
        bestFor: ['writing', 'mixed'],
        features: ['Custom brand voices', 'Enterprise-grade security', 'SSO', 'Dedicated account manager'],
        officialPricingUrl: 'https://www.jasper.ai/pricing',
        verifiedDate: '2026-05-21',
      },
    ],
  },
};
